version: "3.4"

services:
  php:
    build: 
      context: ./backend/
      dockerfile: Dockerfile.dev
    deploy:
      replicas: 5
    environment:
      APP_ENV: prod
      APP_SECRET: dskcspkmcsdc
      
      DB_DRIVER: ${DB_DRIVER:-pdo_mysql}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-app}
      DB_PASSWORD: ${DB_PASSWORD:-app}
      DB_NAME: ${DB_NAME:-app}
    ports:
      - 8080:80  
    volumes:
      - dbdata:/var/lib/mysql
    depends_on:
      - database
    restart: unless-stopped
  database:
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped 
volumes:
  dbdata:
